# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CocoapodsDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CocoapodsDemo
  pod 'SVProgressHUD'
  pod 'Alamofire', '~> 5.4'
  pod 'SDWebImage', '4.0'

end
